### ISSUE TITLE
App not listing/adding tasks entries

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/aspnet-todo-rest-sample#3] opened 2016-07-30 00:58 UTC
Hi,
I'm preparing the demo for the SPSNYC tomorrow and the app is not adding/listing entries for tasks.
The issue is caused by the fact that tables('toDoList') gives 404 in the excel helper.
I Had to replace it by tables('1') to get it to work.
I wonder if it's a temporary issue with the beta graph API or if I should submit a PR?
Also it might be related to the fact that the user I'm testing against in office 365 is set up in french.

**Comment by jamescro** [comment] 2016-08-02 15:39
Were you able to get this working? I haven't been able to reproduce this. I downloaded a fresh copy of the solution, ran it with a newly registered client, and the sample worked as-is. Can you verify that the ToDoList workbook was uploaded to your OneDrive?

**Comment by baywet** [comment] 2016-08-02 17:05
Hi James, Thanks for the reply.
I had the file on onedrive. And I got some parts to work fixing the urls as I was saying. I think the problem is related to the fact the account was set up in french.

**Comment by jamescro** [comment] 2016-08-02 17:09
Thanks for that feedback. I'll look into whether this can be updated to work more smoothly across locales.

**Comment by baywet** [comment] 2016-08-03 13:22
Let me know if you need more information on the subject

**Comment by jamescro** [comment] 2017-01-20 19:54
Closing for now. It looks like we should add a work item for making this work in other locales.

**Closed as completed by jamescro** 2017-01-20 19:54 UTC
